OBJECTS = \
	FishWorld.class \
	FishWorld$$FishWorldKeyAdapter.class \
	FishWorld$$FishWorldMouseAdapter.class \
	Fish.class \
	Highscore.class

%.class: %.java
	javac FishWorld.java

all: $(OBJECTS)

clean:
	rm -f *.class
